### ISSUE TITLE
Crafting Recipes grouped, but shouldn't be?

### ISSUE THREAD

**Issue by BrekiTomasson** [kestalkayden/Lonsdaleite#1]
When building Lonsdaleite items in a crafting table, every single recipe is grouped into a single entry, making it very difficult to find exactly what it is you're looking for. Might I suggest removing `"group": "lonsdaleite"` from your recipe JSON files so that these items appear as separate entries?

**Comment by kestalkayden** [comment]
Ahh. Apologies about that. I made the change and am pushing another update tonight. 

Still learning on this end, but trying to dive right in. That is a remnant from an early test.

Thanks!

**Comment by kestalkayden** [comment]
Ungrouped in 1.0.13.
