### ISSUE TITLE
Odd behavior with Omnitool

### ISSUE THREAD

**Issue by BrekiTomasson** [kestalkayden/Lonsdaleite#2]
In the "Biomes You'll Go" mod, there's a block called `ametrine_ore`, which requires you to use a Netherite pickaxe if you want to get the `ametrine_gems` inside. I tried mining this block with the two pickaxes and the two Omnitools from this mod, and these are the somewhat surprising results:

- Lonsdaleite Pickaxe: FAIL
- Lonsdaleite Omnitool: FAIL
- Perfect Lonsdaleite Pickaxe: SUCCESS
- Perfect Lonsdaleite Omnitool: FAIL

Reading through your code, I'm not exactly sure how the Perfect Lonsdaleite Pickaxe managed to mine the block when the Perfect Lonsdaleite Omnitool failed, but I'm fairly sure that the expected outcome here should be that both succeed or both fail, right?

**Comment by BrekiTomasson** [comment]
I've done some more testing with ores from other mods and these tools, and the behavior is very odd and inconsistent. The Lonsdaleite pickaxe can mine Anthracite Ore (from "Biomes You Go"), but not Ametrine ore and Pendorite ore. The Perfect Lonsdaleite Pickaxe can mine all three, however. The Omnitools, though, can't mine **any** of those ores.

**Comment by BrekiTomasson** [comment]
I have now fixed this (and certain other problems that I found along the way) and created a pull request.

**Comment by kestalkayden** [comment]
Thank you for the pull requests. I appreciate! Admittedly, I also didn't get a notification of your pull requests or issues so I apologize on the delay. I'll be uploading the new release today.
