### ISSUE TITLE
"Durability Remaining" tooltip

### ISSUE THREAD

**Issue by BrekiTomasson** [kestalkayden/Lonsdaleite#3]
Why is this being added to your items? I mean; no other item in the entire game has a tooltip with the durability of the item, and for people running with Advanced Tooltips shown(F3 + H), this is just an unneccessary repetition. If you want to include it, I suggest you either hide it behind a "Must hold shift to display" or make it a configuration option so that people can enable/disable this particular "feature".

Attaching screenshot of how it looks with Advanced Tooltips shown:

![image](https://user-images.githubusercontent.com/7026735/105651209-7b435080-5eb6-11eb-9260-34be11bc015f.png)

**Comment by BrekiTomasson** [comment]
The removal of these tooltips is also included in the pull request I have opened.

**Comment by kestalkayden** [comment]
This is a good point and I agree.
